CREATE TABLE IF NOT EXISTS orders(
ID SERIAL PRIMARY KEY,
user_id INTEGER NOT NULL,
FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE,
status_id INTEGER NOT NULL,
FOREIGN KEY (status_id) REFERENCES statuses(id) ON DELETE CASCADE
)
;

CREATE TABLE IF NOT EXISTS statuses(
ID SERIAL PRIMARY KEY,
name VARCHAR(10) NOT NULL UNIQUE
)
;

CREATE TABLE IF NOT EXISTS users(
ID SERIAL PRIMARY KEY,
name VARCHAR(24) NOT NULL,
email VARCHAR(24) NOT NULL UNIQUE
)
;

CREATE TABLE IF NOT EXISTS categories(
ID SERIAL PRIMARY KEY,
name VARCHAR(24) UNIQUE NOT NULL
)
;

CREATE TABLE IF NOT EXISTS products(
ID SERIAL PRIMARY KEY,
title VARCHAR(36) NOT NULL,
descr VARCHAR(140),
category_id INTEGER NOT NULL,
FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
)
;

CREATE TABLE IF NOT EXISTS order_items(
ID SERIAL PRIMARY KEY,
order_id INTEGER NOT NULL,
FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
product_id INTEGER NOT NULL,
FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
)
;



